apiVersion: v1
kind: Pod
metadata:
  labels:
    run: wlpod
  name: wlpod
spec:
  containers:
  - name: container-webserver1
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts: 
      - mountPath: /volume
        name: volume-emptydir
    resources: 
      limits:     
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  - name: container-webserver2
    image: nginx
    volumeMounts:
      - mountPath: /volume
        name: volume-emptydir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
    args:
    - sleep
    - "1800"
  - name: container-webserver3
    image: nginx
    volumeMounts:
      - mountPath: /volume
        name: volume-emptydir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
    args:
    - sleep
    - "1800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: volume-emptydir
      emptyDir:
        sizeLimit: 256Mi
