apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    fruta: banana
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 8
  revisionHistoryLimit: 10
  selector: 
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels: 
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx-opa
        resources: 
          limits:
            cpu: 0.9
            memory: 256Mi
          requests:
            cpu: 0.4
            memory: 64Mi
